const mongoose = require("mongoose");

const meetingSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
    },

    description: {
      type: String,
      default: "",
    },

    organizer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    participants: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
    ],

    meetingCode: {
      type: String,
      unique: true,
      required: true,
    },

    // Google Meet URL
    meetingUrl: {
      type: String,
      default: "",
    },

    scheduledAt: {
      type: Date,
      required: true,
    },

    duration: {
      type: Number,
      default: 60,
    },

    // User-written notes
    notes: {
      type: String,
      default: "",
    },

    // Transcript generated by Nylas
    transcript: {
      type: String,
      default: "",
    },

    // AI-generated / Nylas summary
    summary: {
      type: String,
      default: "",
    },

    // AI-generated key points
    keyPoints: [
      {
        type: String,
      },
    ],

    // AI-generated action items
    actionItems: [
      {
        type: String,
      },
    ],

    // Decisions made during meeting
    decisions: [
      {
        type: String,
      },
    ],

    // Deadlines mentioned
    deadlines: [
      {
        type: String,
      },
    ],

    // Nylas Notetaker ID
    notetakerId: {
      type: String,
      default: "",
    },

    // Nylas Notetaker status
    notetakerStatus: {
      type: String,
      default: "",
    },

    // Recording URL
    recordingUrl: {
      type: String,
      default: "",
    },

    // Recording duration in seconds
    recordingDuration: {
      type: Number,
      default: 0,
    },

    // Uploaded files
    files: [
      {
        filename: String,
        path: String,
      },
    ],

    attachments: [
      {
        fileName: {
          type: String,
        },

        fileUrl: {
          type: String,
        },

        uploadedAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],

    // Extracted text from uploaded files
    fileContents: {
      type: String,
      default: "",
    },

    status: {
      type: String,
      enum: ["scheduled", "live", "completed", "cancelled"],
      default: "scheduled",
    },
  },
  {
    timestamps: true,
  },
);

module.exports = mongoose.model("Meeting", meetingSchema);
